### ISSUE TITLE
"Deploy via ioPay" shall keep trying to connect with ioPay 

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-studio#39]
<img width="803" alt="Screen Shot 2020-08-07 at 9 20 47 PM" src="https://user-images.githubusercontent.com/989846/89702230-ddea6500-d8f3-11ea-851b-95322a925081.png">

For now, the user compiles the contract, tries in JVM, switches to "Deploy via ioPay" (need a capital "D"), he still sees the simulated accounts which is confusing.

"Deploy via ioPay" should keep trying to connect with ioPay as many users will first switch to "Deploy via ioPay" and open up ioPay desktop. Once connected to ioPay Desktop, the simulated accounts should disappear.

**Comment by uu-z** [comment]
done. currently, if ide connects to iopay-desktop failed. it’s will show a warning and reconnect every 5 seconds.
